import { describe, it, expect } from "vitest";
import fixtureFile from "./fixtures.json";
import {
  BaziInputError,
  computeChart,
  deltaTSeconds,
  describeBalance,
  describeDayMaster,
  describeElement,
  DAY_MASTER_INSIGHTS,
  EARTHLY_BRANCHES,
  ELEMENT_INSIGHTS,
  ELEMENTS,
  findSunLongitudeInstant,
  HEAVENLY_STEMS,
  JIE_TERMS,
  jieTermInstant,
  julianDay,
  julianDayNumber,
  SEXAGENARY_NAMES,
  sexagenaryIndex,
  sexagenaryName,
  solarTermAt,
  sunApparentLongitude,
  sunApparentLongitudeAt,
  sunApparentLongitudeLowAccuracy,
  tenGodOf,
  type BaziChart,
  type BirthInput,
} from "./index";

const MINUTE = 60_000;

function chart(date: string, time: string, utcOffsetMinutes = 480): BaziChart {
  return computeChart({ date, time, utcOffsetMinutes });
}

function names(c: BaziChart): string {
  const { year, month, day, hour } = c.pillars;
  return [year.name, month.name, day.name, hour.name].join(" ");
}

describe("data tables", () => {
  it("has 10 stems, 12 branches, 12 jie terms and 60 distinct sexagenary names", () => {
    expect(HEAVENLY_STEMS.map((s) => s.char).join("")).toBe("甲乙丙丁戊己庚辛壬癸");
    expect(EARTHLY_BRANCHES.map((b) => b.char).join("")).toBe("子丑寅卯辰巳午未申酉戌亥");
    expect(EARTHLY_BRANCHES.map((b) => b.animal)).toEqual([
      "Rat", "Ox", "Tiger", "Rabbit", "Dragon", "Snake", "Horse", "Goat", "Monkey", "Rooster", "Dog", "Pig",
    ]);
    expect(JIE_TERMS.map((t) => `${t.name}${t.longitude}`).join(" ")).toBe(
      "立春315 惊蛰345 清明15 立夏45 芒种75 小暑105 立秋135 白露165 寒露195 立冬225 大雪255 小寒285",
    );
    expect(new Set(SEXAGENARY_NAMES).size).toBe(60);
    expect(SEXAGENARY_NAMES[0]).toBe("甲子");
    expect(SEXAGENARY_NAMES[59]).toBe("癸亥");
    expect(HEAVENLY_STEMS[0].pinyin).toBe("jiǎ");
  });

  it("lists the standard hidden stems in main / middle / residual order", () => {
    const hidden = Object.fromEntries(
      EARTHLY_BRANCHES.map((b) => [b.char, b.hiddenStems.map((i) => HEAVENLY_STEMS[i].char).join("")]),
    );
    expect(hidden).toEqual({
      子: "癸", 丑: "己癸辛", 寅: "甲丙戊", 卯: "乙", 辰: "戊乙癸", 巳: "丙戊庚",
      午: "丁己", 未: "己丁乙", 申: "庚壬戊", 酉: "辛", 戌: "戊辛丁", 亥: "壬甲",
    });
    for (const b of EARTHLY_BRANCHES) expect(HEAVENLY_STEMS[b.hiddenStems[0]].element).toBe(b.element);
  });

  it("maps stem/branch pairs to sexagenary indices and back", () => {
    for (let i = 0; i < 60; i++) {
      expect(sexagenaryIndex(i % 10, i % 12)).toBe(i);
      expect(sexagenaryName(i)).toBe(SEXAGENARY_NAMES[i]);
    }
    expect(() => sexagenaryIndex(0, 1)).toThrow(RangeError); // 甲丑 does not exist
  });

  it("freezes shared records so charts cannot corrupt them", () => {
    expect(Object.isFrozen(HEAVENLY_STEMS)).toBe(true);
    expect(Object.isFrozen(EARTHLY_BRANCHES[1].hiddenStems)).toBe(true);
  });
});

describe("astronomy", () => {
  it("computes Julian Day Numbers and Julian Days", () => {
    expect(julianDayNumber(2000, 1, 1)).toBe(2451545);
    expect(julianDayNumber(1949, 10, 1)).toBe(2433191);
    expect(julianDay(Date.UTC(2000, 0, 1, 12))).toBe(2451545);
    for (const [y, m, d] of [[1900, 3, 1], [1970, 1, 1], [2024, 2, 29], [2100, 12, 31]]) {
      expect(julianDayNumber(y, m, d)).toBe(Date.UTC(y, m - 1, d) / 86_400_000 + 2440588);
    }
  });

  it("uses the Espenak–Meeus ΔT polynomials", () => {
    expect(deltaTSeconds(1950)).toBeCloseTo(29.07, 2);
    expect(deltaTSeconds(2000)).toBeCloseTo(63.86, 2);
    expect(deltaTSeconds(1900)).toBeCloseTo(-2.79, 2);
  });

  it("reproduces Meeus example 25.a (low accuracy) and 25.b (VSOP87) for 1992 Oct 13.0 TD", () => {
    // Meeus 25.a prints λ = 199.90895° with the rounded nutation/aberration shortcut; our fuller
    // correction differs by ~0.0003°. The reference for 25.b comes from PyEphem (199.906009°).
    expect(Math.abs(sunApparentLongitudeLowAccuracy(2448908.5) - 199.90895)).toBeLessThan(0.0005);
    expect(Math.abs(sunApparentLongitude(2448908.5) - 199.906009)).toBeLessThan(0.0003);
  });

  it("finds the 2024 and 2025 立春 instants (published ≈ 08:27 and 14:10 UTC) within ±15 minutes", () => {
    const lichun2024 = jieTermInstant(2024, 0);
    const lichun2025 = jieTermInstant(2025, 0);
    expect(Math.abs(lichun2024 - Date.UTC(2024, 1, 4, 8, 27))).toBeLessThan(15 * MINUTE);
    expect(Math.abs(lichun2025 - Date.UTC(2025, 1, 3, 14, 10))).toBeLessThan(15 * MINUTE);
    // In practice the VSOP87 path is much closer than that.
    expect(Math.abs(lichun2024 - Date.UTC(2024, 1, 4, 8, 26, 56))).toBeLessThan(MINUTE);
    expect(Math.abs(lichun2025 - Date.UTC(2025, 1, 3, 14, 10, 15))).toBeLessThan(MINUTE);
  });

  it("matches PyEphem jie instants 1901–2099 to within a minute", () => {
    // [year, jie index, PyEphem UTC instant] — generated by the cross-check script.
    const ref: [number, number, string][] = [
      [1901, 3, "1901-05-06T05:50:35Z"],
      [1950, 0, "1950-02-04T09:20:41Z"],
      [1985, 10, "1985-12-07T04:16:15Z"],
      [2000, 11, "2000-01-06T01:00:32Z"],
      [2033, 5, "2033-07-06T18:24:54Z"],
      [2050, 11, "2050-01-05T04:07:13Z"],
      [2099, 7, "2099-09-07T06:33:27Z"],
    ];
    for (const [year, index, iso] of ref) {
      expect(Math.abs(jieTermInstant(year, index) - Date.parse(iso))).toBeLessThan(MINUTE);
    }
  });

  it("finds equinoxes and keeps the low-accuracy model within its ~0.01° budget", () => {
    const equinox = findSunLongitudeInstant(0, Date.UTC(2024, 2, 1));
    expect(Math.abs(equinox - Date.UTC(2024, 2, 20, 3, 6, 22))).toBeLessThan(MINUTE);
    const lowAcc = findSunLongitudeInstant(315, Date.UTC(2024, 1, 4), sunApparentLongitudeLowAccuracy);
    expect(Math.abs(lowAcc - Date.UTC(2024, 1, 4, 8, 26, 56))).toBeLessThan(15 * MINUTE);
  });

  it("root-finds precisely and picks the crossing nearest the seed", () => {
    const t = findSunLongitudeInstant(135, Date.UTC(2030, 7, 1));
    expect(Math.abs(sunApparentLongitudeAt(t) - 135)).toBeLessThan(1e-5);
    // Any seed within a few months selects the same crossing.
    expect(Math.abs(findSunLongitudeInstant(135, Date.UTC(2030, 4, 1)) - t)).toBeLessThan(1000);
    expect(Math.abs(findSunLongitudeInstant(135, Date.UTC(2030, 10, 1)) - t)).toBeLessThan(1000);
  });

  it("reports the jie term in effect with a consistent span", () => {
    const at = Date.UTC(2024, 1, 4, 9); // after 立春 2024
    const span = solarTermAt(at);
    expect(span.term.name).toBe("立春");
    expect(span.next.name).toBe("惊蛰");
    expect(span.startMs).toBeLessThanOrEqual(at);
    expect(span.endMs).toBeGreaterThan(at);
    expect(solarTermAt(Date.UTC(2024, 1, 4, 8)).term.name).toBe("小寒");
  });
});

describe("computeChart: hand-checkable vectors", () => {
  it("2000-01-01 12:00 UTC+8 → 己卯 丙子 戊午 戊午", () => {
    const c = chart("2000-01-01", "12:00");
    expect(names(c)).toBe("己卯 丙子 戊午 戊午");
    expect(c.utcInstant).toBe("2000-01-01T04:00:00.000Z");
    expect(c.solarYear).toBe(1999);
    expect(c.pillars.day.index).toBe(54);
    expect(c.dayMaster.char).toBe("戊");
    expect(c.solarTerm.name).toBe("大雪");
    expect(c.notes.some((n) => n.startsWith("Born before 立春 (Start of Spring)"))).toBe(true);
  });

  it("1949-10-01 is a 甲子 day", () => {
    const c = chart("1949-10-01", "12:00");
    expect(c.pillars.day.name).toBe("甲子");
    expect(c.pillars.day.index).toBe(0);
  });

  it("changes year and month pillars at 立春 2024 (≈16:27 CST), not on 1 January", () => {
    const before = chart("2024-02-04", "16:00");
    const after = chart("2024-02-04", "17:00");
    expect([before.pillars.year.name, before.pillars.month.name]).toEqual(["癸卯", "乙丑"]);
    expect([after.pillars.year.name, after.pillars.month.name]).toEqual(["甲辰", "丙寅"]);
    expect(before.solarYear).toBe(2023);
    expect(after.solarYear).toBe(2024);
    expect(after.solarTerm).toMatchObject({ name: "立春", english: "Start of Spring", longitude: 315 });
    expect(after.solarTerm.beganAt.startsWith("2024-02-04T08:2")).toBe(true);
    expect(after.solarTerm.next.name).toBe("惊蛰");
    expect(chart("2024-01-20", "12:00").pillars.year.name).toBe("癸卯");
  });

  it("flags births close to a jie boundary", () => {
    const c = chart("2024-02-04", "16:20"); // ~7 minutes before 立春
    const note = c.notes.find((n) => n.includes("boundary"));
    expect(note).toMatch(/^Born \d+ minutes before the 立春 \(Start of Spring\) boundary/);
    expect(note).toContain("month and year pillars");
    expect(chart("2024-02-04", "12:00").notes.some((n) => n.includes("boundary"))).toBe(false);
  });

  it("advances the day pillar at 23:00 (late 子 hour), not at 22:59", () => {
    const at2259 = chart("2024-02-04", "22:59");
    const at2330 = chart("2024-02-04", "23:30");
    const nextDay = chart("2024-02-05", "12:00");
    expect(at2259.pillars.day.name).toBe("戊戌");
    expect(at2259.pillars.hour.name).toBe("癸亥");
    expect(at2330.pillars.day.name).toBe(nextDay.pillars.day.name);
    expect(at2330.pillars.day.name).toBe("己亥");
    expect(at2330.pillars.hour.name).toBe("甲子"); // 五鼠遁: 己 day → 甲子 hour
    expect(at2330.notes.some((n) => n.includes("late 子 (Rat) hour") && n.includes("戊戌"))).toBe(true);
    expect(at2259.notes.some((n) => n.includes("late 子"))).toBe(false);
    // 23:30 on one date and 00:30 on the next share day and hour pillars.
    const lateNight = chart("2024-02-03", "23:30");
    const earlyMorning = chart("2024-02-04", "00:30");
    expect(lateNight.pillars.day.name).toBe(earlyMorning.pillars.day.name);
    expect(lateNight.pillars.hour.name).toBe(earlyMorning.pillars.hour.name);
  });

  it("rolls the day pillar across a year end at 23:00", () => {
    expect(chart("1999-12-31", "23:30").pillars.day.name).toBe("戊午"); // = 2000-01-01
    expect(chart("1999-12-31", "23:30").pillars.year.name).toBe("己卯");
  });

  it("assigns hour branches on odd-hour boundaries", () => {
    const hourBranch = (time: string) => chart("2024-06-15", time).pillars.hour.branch.char;
    expect(["00:59", "01:00", "02:59", "03:00", "12:59", "13:00", "21:00", "22:59", "23:00"].map(hourBranch)).toEqual(
      ["子", "丑", "丑", "寅", "午", "未", "亥", "亥", "子"],
    );
  });

  it("derives month stems with 五虎遁", () => {
    const tigerMonths = [2024, 2025, 2026, 2027, 2028].map((y) => chart(`${y}-02-20`, "12:00").pillars.month.name);
    expect(tigerMonths).toEqual(["丙寅", "戊寅", "庚寅", "壬寅", "甲寅"]);
    expect(chart("1984-06-01", "12:00").pillars.year.name).toBe("甲子");
  });

  it("uses the UTC instant for solar terms and the local date for the day pillar", () => {
    // Same instant (2024-02-04 08:00 UTC, before 立春) seen from UTC+8 and UTC-7.
    const east = chart("2024-02-04", "16:00", 480);
    const west = chart("2024-02-04", "01:00", -420);
    expect(west.utcInstant).toBe(east.utcInstant);
    expect(west.pillars.year.name).toBe("癸卯");
    expect(west.pillars.month.name).toBe(east.pillars.month.name);
    expect(west.pillars.day.name).toBe(east.pillars.day.name); // both local dates are 2024-02-04
    expect(chart("2024-02-04", "02:00", -420).pillars.year.name).toBe("甲辰"); // 09:00 UTC, after 立春
    expect(chart("2024-02-04", "16:00", 0).notes[0]).toContain("UTC+00:00");
    expect(chart("2024-02-04", "16:00", -570).notes[0]).toContain("UTC-09:30");
  });

  it("changes the month pillar exactly at each computed jie instant", () => {
    for (const [year, index] of [[1935, 4], [1978, 0], [2012, 9], [2061, 11]]) {
      const t = jieTermInstant(year, index);
      const at = (ms: number) => {
        const d = new Date(Math.floor(ms / MINUTE) * MINUTE);
        const iso = d.toISOString();
        return computeChart({ date: iso.slice(0, 10), time: iso.slice(11, 16), utcOffsetMinutes: 0 });
      };
      const before = at(t - 2 * MINUTE);
      const after = at(t + 2 * MINUTE);
      expect(before.solarTerm.index).toBe((index + 11) % 12);
      expect(after.solarTerm.index).toBe(index);
      expect(after.pillars.month.branch.index).toBe((before.pillars.month.branch.index + 1) % 12);
    }
  });

  it("computes ten gods, hidden stems and element tallies", () => {
    const c = chart("2000-01-01", "12:00"); // 己卯 丙子 戊午 戊午, Day Master 戊 (Yang Earth)
    expect(c.pillars.day.tenGod).toBeNull();
    expect(c.pillars.year.tenGod?.chinese).toBe("劫财");
    expect(c.pillars.month.tenGod?.chinese).toBe("偏印");
    expect(c.pillars.hour.tenGod?.chinese).toBe("比肩");
    expect(c.pillars.year.hiddenStems.map((h) => [h.stem.char, h.role, h.tenGod.chinese])).toEqual([["乙", "main", "正官"]]);
    expect(c.pillars.day.hiddenStems.map((h) => [h.stem.char, h.role, h.weight, h.tenGod.english])).toEqual([
      ["丁", "main", 1, "Direct Resource"],
      ["己", "middle", 0.5, "Rob Wealth"],
    ]);
    expect(c.elementCounts).toEqual({ wood: 1, fire: 3, earth: 3, metal: 0, water: 1 });
    expect(c.elementScores).toEqual({ wood: 1, fire: 3, earth: 4, metal: 0, water: 1 });
    const residual = chart("1985-12-17", "21:09"); // 乙丑 戊子 庚寅 丁亥: residual qi weighs 0.3
    expect(residual.elementScores).toEqual({ wood: 2.5, fire: 1.5, earth: 2.3, metal: 1.3, water: 2.5 });
    expect(Object.values(residual.elementCounts).reduce((a, b) => a + b)).toBe(8);
  });

  it("is deterministic and JSON-serialisable", () => {
    const a = chart("1990-07-15", "08:05");
    expect(chart("1990-07-15", "08:05")).toEqual(a);
    expect(JSON.parse(JSON.stringify(a))).toEqual(a);
    expect(a.input).toEqual({ date: "1990-07-15", time: "08:05", utcOffsetMinutes: 480 });
    expect(a.notes[0]).toMatch(/no true-solar-time correction/);
  });
});

describe("computeChart: input validation", () => {
  const bad: [string, BirthInput][] = [
    ["non-leap Feb 29", { date: "2023-02-29", time: "12:00", utcOffsetMinutes: 480 }],
    ["1900 is not a leap year", { date: "1900-02-29", time: "12:00", utcOffsetMinutes: 480 }],
    ["month 13", { date: "2024-13-01", time: "12:00", utcOffsetMinutes: 480 }],
    ["month 00", { date: "2024-00-10", time: "12:00", utcOffsetMinutes: 480 }],
    ["day 31 in April", { date: "2024-04-31", time: "12:00", utcOffsetMinutes: 480 }],
    ["unpadded date", { date: "2024-1-5", time: "12:00", utcOffsetMinutes: 480 }],
    ["year before 1900", { date: "1899-12-31", time: "12:00", utcOffsetMinutes: 480 }],
    ["year after 2100", { date: "2101-01-01", time: "12:00", utcOffsetMinutes: 480 }],
    ["hour 24", { date: "2024-06-01", time: "24:00", utcOffsetMinutes: 480 }],
    ["minute 60", { date: "2024-06-01", time: "12:60", utcOffsetMinutes: 480 }],
    ["unpadded time", { date: "2024-06-01", time: "7:30", utcOffsetMinutes: 480 }],
    ["seconds", { date: "2024-06-01", time: "07:30:00", utcOffsetMinutes: 480 }],
    ["offset > 14 h", { date: "2024-06-01", time: "12:00", utcOffsetMinutes: 900 }],
    ["offset < -14 h", { date: "2024-06-01", time: "12:00", utcOffsetMinutes: -841 }],
    ["fractional offset", { date: "2024-06-01", time: "12:00", utcOffsetMinutes: 480.5 }],
    ["NaN offset", { date: "2024-06-01", time: "12:00", utcOffsetMinutes: Number.NaN }],
  ];
  it.each(bad)("rejects %s", (_label, input) => {
    expect(() => computeChart(input)).toThrow(BaziInputError);
    expect(() => computeChart(input)).toThrow(Error);
  });

  it("gives clear messages", () => {
    expect(() => chart("2023-02-29", "12:00")).toThrow('Invalid date "2023-02-29": February 2023 has 28 days.');
    expect(() => chart("1899-12-31", "12:00")).toThrow("Year 1899 is outside the supported range 1900–2100.");
    expect(() => chart("2024-06-01", "12:00", 900)).toThrow(/outside ±840 min/);
  });

  it("accepts the edges of the supported range", () => {
    expect(names(chart("1900-01-01", "00:00", 840))).toMatch(/^己亥 丙子 /);
    expect(names(chart("2100-12-31", "23:59", -720))).toMatch(/^庚申 戊子 /);
    expect(chart("2000-02-29", "12:00").pillars.day.name).toBe("丁巳"); // 戊午 (54) + 59 days
  });
});

describe("ten gods", () => {
  const godsFor = (dm: number) => HEAVENLY_STEMS.map((s) => tenGodOf(dm, s).chinese).join(" ");
  it("follows the element/polarity rules", () => {
    expect(godsFor(0)).toBe("比肩 劫财 食神 伤官 偏财 正财 七杀 正官 偏印 正印"); // 甲
    expect(godsFor(7)).toBe("正财 偏财 正官 七杀 正印 偏印 劫财 比肩 伤官 食神"); // 辛
    expect(tenGodOf(HEAVENLY_STEMS[4], HEAVENLY_STEMS[8]).english).toBe("Indirect Wealth"); // 戊 → 壬
  });
  it("gives every day master each ten god exactly once", () => {
    for (let dm = 0; dm < 10; dm++) expect(new Set(godsFor(dm).split(" ")).size).toBe(10);
  });
});

describe("insights", () => {
  it("describes every day master in 2–3 sentences and every element in one", () => {
    expect(DAY_MASTER_INSIGHTS.map((d) => d.stem).join("")).toBe("甲乙丙丁戊己庚辛壬癸");
    for (const d of DAY_MASTER_INSIGHTS) {
      const sentences = d.text.split(/(?<=[.!?])\s+/).length;
      expect(sentences).toBeGreaterThanOrEqual(2);
      expect(sentences).toBeLessThanOrEqual(3);
    }
    expect(describeDayMaster(HEAVENLY_STEMS[0]).image).toBe("the tall tree");
    for (const el of ELEMENTS) expect(describeElement(el).split(/(?<=[.!?])\s+/)).toHaveLength(1);
    expect(Object.keys(ELEMENT_INSIGHTS)).toHaveLength(5);
  });

  it("frames the balance commentary as a heuristic and names strongest and missing elements", () => {
    const c = chart("2000-01-01", "12:00"); // earth 4, fire 3, wood 1, water 1, metal 0
    const obs = describeBalance(c);
    expect(obs[0]).toMatch(/simplified traditional heuristic, not a full strength analysis/);
    expect(obs[1]).toMatch(/^Earth \(土\) is the most prominent element, with 4 of 9 weighted points/);
    expect(obs[2]).toMatch(/^Metal \(金\) does not appear anywhere in the chart/);
    expect(obs[3]).toContain("Your Day Master 戊 (Yang Earth)");
    expect(describeBalance(c)).toEqual(obs);
  });

  it("handles ties and charts with no missing element", () => {
    const even = { wood: 2, fire: 2, earth: 2, metal: 2, water: 2 };
    const obs = describeBalance({ elementScores: even, dayMaster: HEAVENLY_STEMS[0] });
    expect(obs[1]).toMatch(/^Wood \(木\), Fire \(火\), Earth \(土\), Metal \(金\) and Water \(水\) share the lead/);
    expect(obs[2]).toMatch(/are the least represented elements/);
    expect(obs[3]).toMatch(/about 40%/);
  });
});

interface Fixture {
  input: BirthInput;
  expected: { year: string; month: string; day: string; hour: string };
  nearestJie: string;
  minutesFromJie: number;
  kind: string;
}

describe("reference fixtures (lunar_python EightChar, sect 1)", () => {
  const cases = (fixtureFile as { cases: Fixture[] }).cases;
  it("has ~40 cases mixing ordinary, near-boundary and late-night births", () => {
    expect(cases.length).toBeGreaterThanOrEqual(35);
    expect(new Set(cases.map((c) => c.kind))).toEqual(new Set(["random", "near-jie", "late-night"]));
  });
  for (const f of cases) {
    const nearBoundary = Math.abs(f.minutesFromJie) < 15;
    it.skipIf(nearBoundary)(`${f.input.date} ${f.input.time} → ${Object.values(f.expected).join(" ")}`, () => {
      const c = computeChart(f.input);
      expect({
        year: c.pillars.year.name,
        month: c.pillars.month.name,
        day: c.pillars.day.name,
        hour: c.pillars.hour.name,
      }).toEqual(f.expected);
    });
  }
});
